permalink:      /:categories/:title/

exclude:
    - README.md
    - markup
    - 7bits.iml

nav:
    - name:     Для друзей
      url:      /for-friends

    - name:     Portfolio
      url:      /null/

    - name:     About
      url:      /null/
