permalink:    /:categories/:title/

exclude:
  - README.md
  - markup
  - 7bits.iml
  - nginx-configurations

nav:
  - name:   Портфолио
    url:    /null

  - name:   Студентам и школьникам
    url:    /null

  - name:   Для друзей
    url:    /for-friends.html

  - name:   Связаться с нами
    url:    /null
