permalink:    /:categories/:title/

exclude:
  - README.md
  - markup
  - 7bits.iml
  - nginx-configurations

#jammit_base_dir: ./
#jammit_output_dir: assets

nav:
  - name:   Портфолио
    url:    /portpholio.html

  - name:   Студентам и школьникам
    url:    /for-students.html

  - name:   Для друзей
    url:    /for-friends.html

  - name:   Связаться с нами
    url:    /contact-us.html