pygments:       true
permalink:      /:categories/:title/
paginate:       5

nav:
    - name:     For friends
      url:      /for-friends

    - name:     Portfolio
      url:      /portfolio/

    - name:     About
      url:      /about/
      subnav:
        - name: Contact
          url:  mailto:scott-at-dotcom-after-appden
