permalink:    /:categories/:title/

exclude:
  - README.md
  - markup
  - 7bits.iml
  - nginx-configurations

#jammit_base_dir: ./
#jammit_output_dir: assets

nav:
  # - name:   Портфолио
  #   url:    /portfolio.html

  - name:   Обучение
    url:    /students.html

  - name:   Мероприятия
    url:    /events.html

  - name:   Контакты
    url:    /contacts.html

markdown: kramdown
# auto: true

exclude: portfolio.html, events-archive.html, nginx-configurations