permalink:    /:categories/:title/

exclude:
  - README.md
  - 7bits.iml
  - nginx-configurations
  - portfolio.haml
  - events-archive.haml

#jammit_base_dir: ./
#jammit_output_dir: assets

nav:
  - name:   Обучение
    url:    /students.html

  - name:   Мероприятия
    url:    /events.html

  - name:   Контакты
    url:    /contacts.html

markdown: kramdown
#  auto_ids: false,
#  use_coderay: false
# auto: true